### ISSUE TITLE
Collision capsules for new robot training

### ISSUE THREAD

**Issue by ksalati** [jstmn/ikflow#14]
Hello

I am trying to start a training for Kuka Iiwa14. I have added the URDF file and created a subclass in jrl / robots.py. But i get this when i try to generate dataset or start a training. 

![screenshot](https://github.com/user-attachments/assets/0bd1e4e0-c056-45a9-a314-e6d9147368f3)

Do I necessarily need the collision capsules to start a training now?

**Comment by jstmn** [comment]
Hi,

Collision capsules aren't necessary for training, but there's not a clean way to disable them. It should be pretty easy to add them or change the code so you don't need them though.

 A couple questions:
1. Is the urdf different than the current Iiwa7 urdf in Jrl? If it's different, where is yours from and can we add it to Jrl?
2. Can you include the code of your subclass?

thanks

**Comment by ksalati** [comment]
1.  I found the urdf at this link :[urdf_link](https://github.com/kuka-isir/iiwa_description/tree/master/urdf). I formatted it to be similar to the Iiwa7 in jrl. Here are the original and formatted urdfs :[formated_iiwa14]. (https://github.com/ksalati/init/tree/main/iiwa14). We could add it, but I don't know if it's correct yet.
2.This is the subclass `
class Iiwa14(Robot):
    name = "iiwa14"
    formal_robot_name = "Kuka LBR IIWA14"

    # See
    # Rotational repeatability calculated in calculate_rotational_repeatability.py
    POSITIONAL_REPEATABILITY_MM = 0.1
    ROTATIONAL_REPEATABILITY_DEG = 0.12614500942996015

    def __init__(self, verbose: bool = False):
        active_joints = [
            "joint_0",
            "joint_1",
            "joint_2",
            "joint_3",
            "joint_4",
            "joint_5",
            "joint_6",
        ]
        urdf_filepath = get_filepath("urdfs/iiwa14/iiwa14_formatted.urdf")
        base_link = "world"
        end_effector_link_name = "link_ee_kuka"
        collision_capsules_by_link = None  # TODO

        ignored_collision_pairs = []
        Robot.__init__(
            self,
            Iiwa14.name,
            urdf_filepath,
            active_joints,
            base_link,
            end_effector_link_name,
            ignored_collision_pairs,
            collision_capsules_by_link,
            verbose=verbose,
            additional_link_name=None,
        )

`

**Comment by jstmn** [comment]
Cool thanks. I'll add this to Jrl today.

**Comment by ksalati** [comment]
What role does `dim_latent_space` play when training a model? Does a higher value mean better performance, or is it more relevant with the dimension of dataset?

**Comment by jstmn** [comment]
I don't have a great answer for how to set this unfortunately. I would try 7, 10, and 13.

Through my experiments I never found a definitive trend with this hyperparameter. Just for example, for the kuka7, increasing it to 14 from 8 improved performance, whereas for the panda, 7 was found to be the best.

Adding the robot now!

**Comment by jstmn** [comment]
Just added Iiwa14, see [0b79e1c3edc464621fa61f130ff87fb704cd7bf8](https://github.com/jstmn/jrl/commit/0b79e1c3edc464621fa61f130ff87fb704cd7bf8)

let me know if you have any troubles with it

**Comment by ksalati** [comment]
Thanks !
