### ISSUE TITLE
Many Additional Links When Add Robot

### ISSUE THREAD

**Issue by fengmingyang666** [jstmn/ikflow#15]
I want to add new robot to robots.py in jrl, and I have many additional links. I find that additional_link_names only accept one link, what  should I do?

**Comment by fengmingyang666** [comment]
Like this:
![Screenshot from 2024-07-24 11-31-54](https://github.com/user-attachments/assets/3c1454cd-d148-4ea3-b5f9-e48f4e3c8585)

**Comment by jstmn** [comment]
Unfortunately without a rewrite to the FK functions multiple links for `additional_link` won't be possible. The `additional_link` thing is a hack that's not flexible.

How are `jingbu_link` and `jingbu_link2` connected though? Can you send me a graph showing your urdf (try [this library](https://manpages.ubuntu.com/manpages/trusty/man1/urdf_to_graphiz.1.html))? Maybe there's a way around this without a major code change.

**Comment by fengmingyang666** [comment]
Thanks. I have solved this problem.
I want to know if there is a way to visualize the quality of the generated data set, i.e., I want to see how many joints solutions will have to one pose?
Thank you.

**Comment by jstmn** [comment]
Glad to hear you solved it. 

`scripts/visualize.py --demo_name=oscillate_latent` would be your best bet, with this library at least. If you put together a better tool let me know and we can add it to the repo!

**Comment by fengmingyang666** [comment]
Thanks!
